version: "3.7"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file: .env.docker
    ports:
      - 27017:27017
    volumes:
      - ~/mongo:/data/db

  redis:
    image: redis:latest
    env_file: .env.docker
    container_name: redis
    restart: on-failure
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/backend/config/redis.conf

  backend:
    image: backend:latest
    restart: on-failure
    depends_on:
      - mongodb
      - redis
    env_file: .env.docker
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  nginx:
    image: nginx:latest
    container_name: production_nginx
    env_file: .env.docker
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
  
  jenkins: 
    image: jenkins/jenkins
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./config/data/jenkins:/var/jenkins_home
  
  # terraform: 
  #   image: hashicorp/terraform:latest
  #   container_name: terraform
  #   volumes:
  #     - ./config/terraform:/infra
  #   environment:
  #     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  #     - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
     
