version: "3.4"
services:
  node:
    image: node
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
