version: "3.7"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file: .env.docker
    ports:
      - 27017:27017
    volumes:
      - ~/mongo:/data/db

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    env_file: .env.docker
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./config/redis.conf:/backend/redis/redis.conf
    command: redis-server

  node:
    image: node
    restart: on-failure
    depends_on:
      - mongodb
    env_file: .env.docker
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443