version: "3.4"
services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./go/.env
    ports:
      - "5432:5432"

  go:
    image: go
    restart: on-failure
    depends_on: 
      - db
    env_file:
      - ./go/.env
    build:
      context: ./go
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      
    
  
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443



