version: "3.4"
services:
  client:
    image: client
    restart: on-failure
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules