apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  clusterIP: None
  ports:
    - name: redis
      port: 6379
  selector:
    app: redis

apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-read-service
spec:
  ports:
    - name: redis
      port: 6379
  selector:
    app: redis

    