apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
spec:
  containers:
  - name: dnsutils
    image: k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

  # kubectl apply -f dns.yaml
  # kubectl get pods dns
  # kubectl exec -i -t dnsutils -- nslookup kubernetes.default