apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-lb-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis