apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-service
spec:
  clusterIP: None
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis
