apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim0
  labels:
    app: mongo-claim0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
status: {}